# Generated by Django 4.1.5 on 2023-01-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover_img', models.ImageField(blank=True, upload_to='images')),
                ('category', models.CharField(max_length=80)),
                ('blog_content', models.TextField()),
                ('tag', models.TextField()),
                ('publish', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
