# Generated by Django 4.1.5 on 2023-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
