# Generated by Django 4.1.5 on 2023-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
